// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package llm_test

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// PostJSON provides a mock function for the type MockClient
func (_mock *MockClient) PostJSON(ctx context.Context, url string, body []byte, headers map[string]string) (*http.Response, error) {
	ret := _mock.Called(ctx, url, body, headers)

	if len(ret) == 0 {
		panic("no return value specified for PostJSON")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, map[string]string) (*http.Response, error)); ok {
		return returnFunc(ctx, url, body, headers)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, map[string]string) *http.Response); ok {
		r0 = returnFunc(ctx, url, body, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte, map[string]string) error); ok {
		r1 = returnFunc(ctx, url, body, headers)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_PostJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostJSON'
type MockClient_PostJSON_Call struct {
	*mock.Call
}

// PostJSON is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body []byte
//   - headers map[string]string
func (_e *MockClient_Expecter) PostJSON(ctx interface{}, url interface{}, body interface{}, headers interface{}) *MockClient_PostJSON_Call {
	return &MockClient_PostJSON_Call{Call: _e.mock.On("PostJSON", ctx, url, body, headers)}
}

func (_c *MockClient_PostJSON_Call) Run(run func(ctx context.Context, url string, body []byte, headers map[string]string)) *MockClient_PostJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 map[string]string
		if args[3] != nil {
			arg3 = args[3].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_PostJSON_Call) Return(response *http.Response, err error) *MockClient_PostJSON_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockClient_PostJSON_Call) RunAndReturn(run func(ctx context.Context, url string, body []byte, headers map[string]string) (*http.Response, error)) *MockClient_PostJSON_Call {
	_c.Call.Return(run)
	return _c
}
